# Outputting
timezone: Europe/Madrid
permalink: '/:year/:month/:day/:title'
no_html_extension: true

# Custom data
title: Alejandro Celaya | Blog
subtitle: Software development, agile methodologies and open source projects
my_name: Alejandro Celaya
my_full_name: Alejandro Celaya Alastru√©

# External services
google_analytics_tracking_id: UA-38351554-3
disqus_shortname: acelayablog
