services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    andrewshell.extension.text:
        class: AndrewShell\Twig\Extensions\Text
        tags:
            - { name: twig.extension }
    truncatehtml.twig.extension:
        class: Acelaya\Twig\Extension\TruncateHtmlExtension
        tags:
            - { name: twig.extension }
