# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Alejandro Celaya | Blog
subtitle: Software development, agile methodologies and open source projects
my_name: Alejandro Celaya
my_full_name: Alejandro Celaya Alastru√©
url: https://blog.alejandrocelaya.com

google_analytics_tracking_id: UA-38351554-3
disqus_shortname: acelayablog
